config/routes.rb
Teach::Application.routes.draw do
  resources :navitems

  resources :tests

  resources :users

  resources :areas

  resources :histories

  resources :questions

   root 'areas#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/controllers/areas_controller.rb
# coding: utf-8
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @area }
      else
        format.html { render action: 'new' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :short_name, :description, :area_admin_id, :file)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area, :html => {:multipart => true}) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,'Name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name,'Abt.Kuerzel' %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :description,'Beschreibung' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :file,'Schulungsunterlagen' %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit 'speichern'%>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Fragenkatalog bearbeiten</h1>

<%= render 'form' %>


<%= link_to(image_tag('show.png', :size => "30x30",:title => "Fragenkatalog anzeigen"), @area) %>
<%= link_to(image_tag('back.png', :size => "30x30",:title => "zurück"), areas_path) %>

app/views/areas/index.html.erb
# coding: utf-8
<h1>Fragenkataloge</h1>

<table border="1">
  <thead>
    <tr>
      <th>Aktion</th>
      <th>Name</th>
      <th>Abt.Kuerzel</th>
      <th>Beschreibung</th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td>
        	<%= link_to(image_tag('show.png', :size => "30x30",:title => "Fragenkatalog anzeigen"), area) %>
        	<%= link_to(image_tag('edit.png', :size => "30x30",:title => "Fragenkatalog bearbeiten"), edit_area_path(area)) %>
        	<%= link_to(image_tag('del.png', :size => "30x30",:title => "Fragenkatalog löschen"), area, method: :delete, data: { confirm: 'Sind Sie sicher?' }) %>
        </td>
        <td><%= area.name %></td>
        <td><%= area.short_name %></td>
        <td><%= area.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to(image_tag('add.png', :size => "30x30",:title => "Neuen Fragenkatalog hinzufügen"), new_area_path)%>

app/views/areas/new.html.erb
<h1>Neue Abteilung anlegen</h1>

<%= render 'form' %>

<%= link_to 'zurueck', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @area.short_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @area.description %>
</p>

<p>
  <strong>Area admin:</strong>
  <%= @area.area_admin_id %>
</p>




<%= link_to(image_tag('edit.png', :size => "30x30",:title => "Fragenkatalog bearbeiten"),  edit_area_path(@area)) %> |
<%= link_to(image_tag('back.png', :size => "30x30",:title => "zurück"), areas_path) %>