config/routes.rb
Teach::Application.routes.draw do
  resources :navitems

  resources :tests

  resources :users

  resources :areas

  resources :histories

  resources :questions

   root 'areas#index'

end

app/models/navitem.rb
class Navitem < ActiveRecord::Base
end

app/controllers/navitems_controller.rb
class NavitemsController < ApplicationController
  before_action :set_navitem, only: [:show, :edit, :update, :destroy]

  # GET /navitems
  # GET /navitems.json
  def index
    @navitems = Navitem.all
  end

  # GET /navitems/1
  # GET /navitems/1.json
  def show
  end

  # GET /navitems/new
  def new
    @navitem = Navitem.new
  end

  # GET /navitems/1/edit
  def edit
  end

  # POST /navitems
  # POST /navitems.json
  def create
    @navitem = Navitem.new(navitem_params)

    respond_to do |format|
      if @navitem.save
        format.html { redirect_to @navitem, notice: 'Navitem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @navitem }
      else
        format.html { render action: 'new' }
        format.json { render json: @navitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navitems/1
  # PATCH/PUT /navitems/1.json
  def update
    respond_to do |format|
      if @navitem.update(navitem_params)
        format.html { redirect_to @navitem, notice: 'Navitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @navitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navitems/1
  # DELETE /navitems/1.json
  def destroy
    @navitem.destroy
    respond_to do |format|
      format.html { redirect_to navitems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navitem
      @navitem = Navitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navitem_params
      params.require(:navitem).permit(:name, :url, :rang)
    end
end

app/helpers/navitems_helper.rb
module NavitemsHelper
end

app/views/navitems/_form.html.erb
<%= form_for(@navitem) do |f| %>
  <% if @navitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@navitem.errors.count, "error") %> prohibited this navitem from being saved:</h2>

      <ul>
      <% @navitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rang %><br>
    <%= f.number_field :rang %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/navitems/edit.html.erb
<h1>Editing navitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @navitem %> |
<%= link_to 'Back', navitems_path %>

app/views/navitems/index.html.erb
<h1>Listing navitems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Rang</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @navitems.each do |navitem| %>
      <tr>
        <td><%= navitem.name %></td>
        <td><%= navitem.url %></td>
        <td><%= navitem.rang %></td>
        <td><%= link_to 'Show', navitem %></td>
        <td><%= link_to 'Edit', edit_navitem_path(navitem) %></td>
        <td><%= link_to 'Destroy', navitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Navitem', new_navitem_path %>

app/views/navitems/new.html.erb
<h1>New navitem</h1>

<%= render 'form' %>

<%= link_to 'Back', navitems_path %>

app/views/navitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @navitem.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @navitem.url %>
</p>

<p>
  <strong>Rang:</strong>
  <%= @navitem.rang %>
</p>

<%= link_to 'Edit', edit_navitem_path(@navitem) %> |
<%= link_to 'Back', navitems_path %>